# Generated by Django 5.0.4 on 2024-05-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeCarePro', '0002_job_feedback_payment_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HomeCarePro.services'),
            preserve_default=False,
        ),
    ]
